crm/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

    )
from django.urls import path, include
from leads.views import (
    landing_page,pricing_page,
    services_page,aboutus_page,
    contactus_page,
    LandingPageView,
    SignupView,
    dashboard,
    DashboardView,DownloadLeadsView,UploadCSVView,MatchFieldsView,ProcessDataView,
    # CreateNotificationView, MarkAsReadView, ClearNotificationsView,create_lead_notification
 )
from campaign.views import ContactView
from fb_app.views import fb_callback,fb_test
# from whatsapp.views import whatsapp_callback





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',landing_page , name="landing-page"),
    path('fb_callback/',fb_callback , name="fb_callback"),
    path('fb_login/',fb_test , name="fb_login"),
    # path('whatsapp_callback/',whatsapp_callback , name="whatsapp_callback")
    # path('pricing/',pricing_page , name="pricing-page"),
    path('services/',services_page , name="services-page"),
    path('aboutus/',aboutus_page , name="aboutus-page"),
    # path('setting/',setting_page , name="setting-page"),
    # path('contactus/',contactus_page , name="contactus-page"),
    path('contactus/',ContactView.as_view() , name="contactus-page"),
    path('dashboard/',DashboardView.as_view() , name="dashboard"),
    # path('',LandingPageView.as_view() , name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    # path('membership/', include('membership.urls',namespace="membership")),
    path('campaigns/', include('campaign.urls',namespace="campaigns")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('reset-password/', PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name="password_reset_comfirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    # path('contact/',ContactUsView.as_view(), name='contact')
    path('download/', DownloadLeadsView.as_view(), name='download_leads'),
    # path('upload/', UploadCSVView.as_view(), name='upload'),
    path('upload/', UploadCSVView.as_view(), name='upload'),
    path('match-fields/', MatchFieldsView.as_view(), name='match-fields'),
    path('process-data/', ProcessDataView.as_view(), name='process-data'),
    # path('notifications/create/', CreateNotificationView.as_view(), name='create_notification'),
    # path('notifications/create/', create_lead_notification, name='create_notification'),
    # path('notifications/mark-as-read/<int:notification_id>/', MarkAsReadView.as_view(), name='mark_as_read'),
    # path('notifications/clear/', ClearNotificationsView.as_view(), name='clear_notifications'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#considering production
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls  import path
from .views import (
    lead_list,lead_detail,lead_update,lead_delete,
    LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView,CategoryListView,
    # CategoryDetailView,CategoryCreateView,CategoryUpdateView,CategoryDeleteView,
    LeadCategoryUpdateView,
    FollowUpCreateView,FollowUpUpdateView, FollowUpDeleteView,FollowUpListView,DownloadLeadsView,SettingsPageView,
    # WhatsappMessagingView,
    lead_form_submissions,
    )
from django.conf.urls import handler404,handler400,handler403,handler500
from leads.views import error_404,error_400,error_403,error_500,error_401,error_405
# from campaign.views import AssignAgentView

handler404 = error_404
handler400 = error_400
handler403 = error_403
handler401 = error_401
handler405 = error_405
handler500 = error_500


app_name = "leads"

urlpatterns = [
    path('',LeadListView.as_view(),name="lead-list"),
    path('facebook/',lead_form_submissions,name="facebook-lead-list"),
    # path('<int:campaign_id>/<int:pk>/',LeadDetailView.as_view(),name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/update/', LeadUpdateView.as_view(),name="lead-update"),
    path('<int:campaign_id>/<int:pk>/delete/', LeadDeleteView.as_view(),name="lead-delete"),
    # path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path('<int:campaign_id>/<int:pk>/category/', LeadCategoryUpdateView.as_view(),name="lead-category-update"),
    path('leads/followups/', FollowUpListView.as_view(), name='followup-list'), 
    path('settings', SettingsPageView.as_view(), name='settings'), 
    # path('<int:campaign_id>/followups/', FollowUpView.as_view(), name='followup-leads'),
    path('<int:campaign_id>/<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),    
    path('followups/<int:campaign_id>/<int:pk>/update/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('<int:pk>/create/', LeadCreateView.as_view(),name="lead-create"),
    # path('<int:pk>/whatsapp/', WhatsappMessagingView.as_view(), name='lead-whatsapp'),
    # path('create-category/', CategoryCreateView.as_view(),name="category-create"),
    path('categories/' , CategoryListView.as_view(), name="category-list"),
    # path('categories/<int:pk>/update/' ,CategoryUpdateView.as_view(), name="category-update"),
    # path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(),name="category-delete"),
    # path('categories/' , CategoryDetailView.as_view(), name="category-detail"),
    # path('upload/', UploadFileView.as_view(), name='upload'),


]

leads/views.py
from typing import Any
from django.core.mail import send_mail
import datetime as dt
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic 
from .models import Lead,Agent,Category
from .forms import LeadModelForm,LeadForm,CustomUserCreationForm,AssignAgentForm,LeadCategoryUpdateForm,CategoryModelForm,FollowUpModelForm
from agents.mixins import OrganiserAndLoginRequiredMixin
# from facebook import GraphAPI
from .models import LeadFormSubmission,FollowUp
from itertools import groupby
from campaign.views import Campaign
from django.utils import timezone
from django.db.models import Count, Q, Sum,Max
from django.utils.timezone import make_aware
from datetime import timedelta, datetime
from django.views.generic import ListView,TemplateView
from django.db.models import Count
from .models import Lead, Category, FollowUp
from datetime import date
from django.views import View
# from twilio.rest import Client
from django.core.mail import EmailMessage
from campaign.forms import ContactForm
from django import forms, http
# from .models import Notification
from django.utils.datetime_safe import datetime
import csv


#CRUD - create,retreive,update,delete + list


def lead_form_submissions(request):
    submissions = LeadFormSubmission.objects.all()
    context = {'submissions': submissions}
    return render(request, 'lead_form_submissions.html', context)


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    
    def get_success_url(self):
        return reverse("login") 



class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("dashboard")
        return super().dispatch(request, *args, **kwargs)


def landing_page(request):
    return render(request,"landing.html")


def pricing_page(request):
    return render(request,"pricing.html")

def services_page(request):
    return render(request,"services.html")

def contactus_page(request):
    return render(request,"contactus.html")

def aboutus_page(request):
    return render(request,"aboutus.html")

def dashboard(request):
    return render(request,"dashboard.html")

def setting_page(request):
    return render(request,"setting.html")




class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        converted_category = Category.objects.get(name="Converted")
        followup_category = Category.objects.get(name="Follow Up")
        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')        
        if user.is_organiser:
            campaigns = Campaign.objects.filter(organisation=user.userprofile)          
            # How many leads we have in total
            total_campaign_count = Campaign.objects.filter(organisation=user.userprofile).count()
            
# Total leads converted in a date range       
            if start_date_str and end_date_str:
                start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
                end_date = datetime.strptime(end_date_str, "%Y-%m-%d") + timedelta(days=1)
            else:
                end_date = timezone.now()
                start_date = end_date - timedelta(days=30)
# data for graph 
            leads_converted_in_date_range = Lead.objects.filter(
                Q(category=converted_category),
                Q(converted_date__range=[start_date, end_date]),
                Q(campaign__organisation=user.userprofile)
            ).count()

            total_lead_count_date = Lead.objects.filter(
                Q(campaign__organisation=user.userprofile),
                Q(date_added__range=[start_date, end_date])
            ).count()

            new_lead_count_date = Lead.objects.filter(
                Q(category=Category.objects.get(name="New")),
                Q(campaign__organisation=user.userprofile),
                Q(date_added__range=[start_date, end_date])
            ).count()
            rejected_in_date_range = Lead.objects.filter(
                Q(rejected_date__range=[start_date, end_date]),
                Q(campaign__organisation=user.userprofile)
            ).count()

            followup_in_date_range = Lead.objects.filter(
                Q(followup_date__range=[start_date, end_date]),
                Q(campaign__organisation=user.userprofile)
            ).count()            
         
           
        else:
            campaigns = Campaign.objects.filter(organisation = user.agent.organisation).filter(agent__user = user)   
            # How many leads we have in total
            total_campaign_count = Campaign.objects.filter(organisation = user.agent.organisation).filter(agent__user = user).count()
            
# Total leads converted in a date range       
            if start_date_str and end_date_str:              
                start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
                end_date = datetime.strptime(end_date_str, "%Y-%m-%d") + timedelta(days=1)
            else:
                end_date = timezone.now()
                start_date = end_date - timedelta(days=30)
            leads_converted_in_date_range = Lead.objects.filter(
                Q(category=converted_category),
                Q(converted_date__range=[start_date, end_date]),
                Q(campaign__organisation = user.agent.organisation)
            ).filter(campaign__agent__user = user).count()
            total_lead_count_date = Lead.objects.filter(
                Q(campaign__organisation = user.agent.organisation),
                Q(date_added__range=[start_date, end_date])
            ).filter(campaign__agent__user = user).count()
            new_lead_count_date = Lead.objects.filter(
                Q(category=Category.objects.get(name="New")),
                Q(campaign__organisation = user.agent.organisation),
                Q(date_added__range=[start_date, end_date])
            ).filter(campaign__agent__user = user).count()
            rejected_in_date_range = Lead.objects.filter(
                Q(rejected_date__range=[start_date, end_date]),
                Q(campaign__organisation = user.agent.organisation)
            ).filter(campaign__agent__user = user).count()
            followup_in_date_range = Lead.objects.filter(
                Q(followup_date__range=[start_date, end_date]),
                Q(campaign__organisation = user.agent.organisation)
            ).filter(campaign__agent__user = user).count()               
            
        chart_data = {
            "labels": ["Converted", "Rejected", "Follow-up", "New", ],
            "datasets": [{
                "data": [
                    leads_converted_in_date_range,
                    rejected_in_date_range,
                    followup_in_date_range,
                    new_lead_count_date
                ],
                "backgroundColor": [
                    '#00ff89',   # Converted Leads
                    '#bf0b16',    # Rejected Leads
                    '#0075ff',    # Follow-up Leads
                    '#ffcc19',     # New Leads
                    '#937dc2',    #Total Leads
                ],
                "borderColor": [
                    'rgb(255, 99, 132)',
                    'rgb(255, 206, 86)',
                    'rgb(54, 162, 235)',
                    'rgb(75, 192, 192)'
                ],
                "borderWidth": 1
            }]
        } 
        table_id="example1"       
        context.update({
            "campaigns":campaigns,
            "table_id":table_id,
            "rejected_in_date_range": rejected_in_date_range,
            "followup_in_date_range": followup_in_date_range,
            "total_lead_count_date": total_lead_count_date,
            "new_lead_count_date": new_lead_count_date,
            "total_campaign_count": total_campaign_count,
            "chart_data": chart_data,
            "start_date_str": start_date_str,
            "end_date_str": end_date_str,
            "leads_converted_in_date_range": leads_converted_in_date_range,
            
        })
        return context


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"
    
    def get_queryset(self):
        user = self.request.user
        
        # Get the campaigns of the current user
        campaigns = Campaign.objects.filter(Q(organisation = user.userprofile) | Q(organisation = user.agent.organisation))
        
        # Get the leads associated with these campaigns
        queryset = Lead.objects.filter(campaign__in=campaigns)

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
            
        return context
   

#display leads list
def lead_list(request):
    #return HttpResponse("hello world")
    leads=Lead.objects.all()
    context={
        "leads":leads
    }
    return render(request,'leads/lead_list.html',context)



class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"  

    def get_queryset(self):
        user = self.request.user
        # Get the campaign ID from the URL parameter
        campaign_id = self.kwargs.get('campaign_id')
        # Get the campaign object based on the ID
        campaign = get_object_or_404(Campaign, id=campaign_id)

leads/templates/leads/assign_agent.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>

    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
      <div>
        <button class="button" style="margin:10px 0 50px auto;">
            <a href="{% url 'leads:lead-list' %}" >Go back to leads</a>
        </button>
    </div>

   

    <hr>
    <h1>Assign an agent to this lead</h1>


    <form method="post">
        {%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="button"  >Submit</button>
    </form>

</div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

leads/templates/leads/category_list copy1.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h2>Categories</h2>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Category Name</th>
            <th>Lead Count</th>
            <th>FollowUp Count</th>
            <th>Next FollowUp Date</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for category in category_list %}
            <tr>
              <td>{{ category.name }}</td>
              <td>{{ category.lead_count }}</td>
              <td>{{ category.followup_count }}</td>
              <td>{% if category.next_followup %}{{ category.next_followup|date:"M d, Y" }}{% else %}N/A{% endif %}</td>
              {% comment %} <td><a href="{% url 'leads:lead-category-update' campaign_id=lead.campaign_id pk=lead.pk%}" class="btn btn-primary btn-sm">Edit</a></td> {% endcomment %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

leads/templates/leads/followup_create.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>



    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
    <div>
    <h1 class="h1">Create a New Lead</h1>
            <a href="{% url 'leads:lead-detail' campaign_id=lead.campaign_id pk=lead.pk %}" >
                <button class="flex flex-col items-center justify-center ">
                    <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                        <img src="{% static 'images/goback.png' %}"  alt="" class="w-6 ">
                    </div>
                    <p class="text-gray-700 text-sm mt-2 "> Go Back</p>
                </button>
            </a>
        {% comment %} </button> {% endcomment %}
    </div>

    <form method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="button">Submit</button>
    </form>
</div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "main.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;    
      }
      .button a{
        color: aliceblue;    
      }
    </style>    
 
      <!-- Content -->    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->
            <section class="flex flex-col justify-center flex-wrap items-center mt-10 pt-0">
              <div class="container px-5  mx-auto">
              <div class="basic flex flex-row flex-wrap">
                <div class="icon w-20 h-20 p-0 border rounded-full mr-10">
                    <img src="{% static 'images/user1.jpg' %}" alt="" class="w-20 h-20 rounded-full">
                </div>
                <div class="text-main flex flex-col">
                  <h3 class="text-3xl font-bold">{{lead.first_name}}</h3>
                  <p>Email: {{lead.email}}</p>
                  <p>Status: {{lead.category}}</p>
                  <div class="flex  flex-row flex-wrap gap-5  py-2">
                      <span class="text-gray-500">Staff:</span>
                      <div class=" text-gray-900  flex flex-row flex-wrap gap-2">                        
                            {% for agent in lead.campaign.agent.all %}      
                              <p class=" staff-badge rounded-xl  shadow px-3 text-center mb-2 " style="min-width:50px">{{ agent.user.username }}</p>
                            {% endfor %}                       
                      </div>
                    </div>     
                  <div class="buttons flex flex-row justify-between gap-5 pt-5 flex-wrap border-t border-gray-200">                      
                      <a href="{% url 'leads:lead-detail' campaign_id=lead.campaign_id pk=lead.pk %}" >
                          <button class="flex flex-col items-center justify-center ">
                            <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                              <img src="{% static 'images/goback.png' %}"  alt="" class="w-6 ">
                            </div>
                            <p class="text-gray-700 text-sm mt-2 "> Go Back</p>
                          </button>
                      </a>                                       
                  </div>
                </div>
              </div>
              <hr class="mt-5">
              <div class="detailed pt-5 max-w-screen-sm">
                  <form method="post" class="max-w-xs">
                      {%csrf_token%}
                      {{form|crispy}}
                      <button type="submit" class="button">Submit</button>
                  </form>
              </div>      
            </div>                   
          </section> 
      </div>
    <!-- End of content --> 
    </div>
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}></script>
    {% endblock content %}
    
    
    
    
    
        
      
       

leads/templates/leads/lead_update.html
{% extends "main.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;    
      }
      .button a{
        color: aliceblue;    
      }
    </style>    
      <!-- Content -->    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->
            <section class="flex flex-col justify-center flex-wrap items-center">
              <div class="container px-5 py-24 mx-auto">
              <div class="basic flex flex-row flex-wrap">
                <div class="icon w-20 h-20 p-0 border rounded-full mr-10">
                    <img src="{% static 'images/user1.jpg' %}" alt="" class="w-20 h-20 rounded-full">
                </div>
                <div class="text-main flex flex-col">
                  <h3 class="text-3xl font-bold">{{lead.first_name}} {{lead.last_name}}</h3>
                  <p>Email: {{lead.email}}</p>
                  <p>Status: {{lead.category}}</p>
                  <p>Agent: {{lead.agent}}</p>      
                  <div class="buttons flex flex-row justify-between gap-5 mt-5 flex-wrap">
                      {% comment %} <a href="tel:+{{lead.phone_number}}">
                        <button class="button">
                          <i class="bx bxs-phone-call"></i>
                          Call
                        </button>
                      </a>  
                      <a href="mailto:{{lead.email}}">
                        <button class="button">
                          <i class="bx bxs-send"></i>
                          Email
                        </button>
                      </a>
                      <a href="{% url 'leads:lead-category-update' campaign_id=lead.campaign_id pk=lead.pk %}" >
                        <button class="button">
                          Status
                        </button>
                      </a> {% endcomment %}
                      <!-- s -->
                      {% if request.user.is_organiser  %}
                        <a href="{% url 'leads:lead-delete' campaign_id=lead.campaign_id pk=lead.pk %}">
                        <button class="button ">
                          Delete
                        </button>
                        </a>  
                      {% endif %}
                     
                  </div>
                </div>
              </div>
              <div class="detailed max-w-screen-sm">
                  <h1 class="mt-5 text-3xl font-bold"></h1>
                  <form method="post">
                    {%csrf_token%}
                    {{form|crispy}}
                    <button type="submit" class="button">Submit</button>
                  </form>
              </div>      
            </div>
                   
          </section> 
      </div>
    <!-- End of content --> 
    </div>
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}></script>
    {% endblock content %}
    
    
    
    
    
        
      
       

leads/templates/leads/match_fields.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin:30px auto;
            max-width: 500px;
            display: flex;
            flex-direction:column ;
            align-items: start;
            justify-content: center;
        }
        label{
          text-transform: capitalize;
        }
        select{
          width: 90%;
          max-width: 400px;
          border: 1px solid rgba(128, 128, 128, 0.544);
          height: 40px;
          border-radius: 5px;
          box-shadow: 1px 2px 13px 3px rgba(80, 78, 78, 0.1274);
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;
            width: fit-content;
        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }

    </style>

    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
    <div>
   <div class="flex justify-between items-center my-10">
    <h1 class="text-1xl font-bold text-gray-500  ">Map CSV Fields to Model Fields</h1>
    <button class="button" style="margin: auto;">
      <a href="{% url 'leads:category-list' %}" >Go back</a>
    </button>
   </div>
    


<h1 class="text-2xl font-bold ">Match Fields</h1>
<span style="display: block;height: 1px;background-color: gray;width:150px"></span>

<form method="post">
  {% csrf_token %}

  {% for column in csv_columns %}
    <label for="field_{{ forloop.counter0 }}">{{ column }}</label>
    <select name="field_{{ forloop.counter0 }}">
      <option value="">-- Select Field --</option>
      {% for field_name in lead_fields %}
        <option value="{{ field_name }}">{{ field_name }}</option>
      {% endfor %}
    </select>
    <br>
  {% endfor %}

  <label for="campaign">Campaign</label>
  <select name="campaign">
    <option value="">-- Select Campaign --</option>
    {% for campaign in campaigns %}
      <option value="{{ campaign.name }}">{{ campaign.name }}</option>
    {% endfor %}
  </select>
  <br>

  {% if mapping_error %}
    <p>{{ mapping_error }}</p>
  {% endif %}

  <button class="button " type="submit">Process Data</button>
</form>







{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}
 
</div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

leads/templates/leads/notifications.html
{% comment %} {% extends 'base.html' %}

{% block content %} {% endcomment %}
 <!-- notifications.html -->
  <h1>Notifications</h1>
  {% comment %} <ul>
    {% for notification in notifications %}
      <li>
        <strong>{{ notification.message }}</strong> - {{ notification.timestamp }}
        {% if not notification.is_read %}
          <a href="{% url 'mark_as_read' notification.id %}">Mark as Read</a>
        {% endif %}
      </li>
    {% empty %}
      <li>No notifications</li>
    {% endfor %}
  </ul>
  <a href="{% url 'clear_notifications' %}">Clear Notifications</a> {% endcomment %}


{% comment %} {% endblock %} {% endcomment %}

leads/templates/leads/whatsapp_confirm.html
{% extends 'base.html' %}

{% block content %}
  <h1>WhatsApp message confirmation</h1>
  <p>A WhatsApp message will be sent to {{ lead.whatsapp_number }} shortly.</p>
{% endblock %}