agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name = 'agents'


urlpatterns = [
    path('',AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/' , AgentDetailView.as_view(),name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),
    path('create/',AgentCreateView.as_view(), name='agent-create'),


]

campaign/urls.py
from django.urls import path
from .views import CampaignListView,CampaignCreateView,CampaignDetailView,CampaignUpdateView,CampaignDeleteView,AssignAgentView,CampaignAddAgentView


app_name = 'campaign'

urlpatterns = [
    path('',CampaignListView.as_view(), name='campaign-list'),
    path('<int:pk>/' , CampaignDetailView.as_view(),name='campaign-detail'),
    path('<int:pk>/update/',CampaignUpdateView.as_view(), name='campaign-update'),
    path('<int:pk>/delete/',CampaignDeleteView.as_view(), name='campaign-delete'),
    path('create/',CampaignCreateView.as_view(), name='campaign-create'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path("campaign/<int:pk>/add-agent/", CampaignAddAgentView.as_view(), name="campaign-add-agent"),
    




]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

    )
from django.urls import path, include
from leads.views import (
    landing_page,pricing_page,
    services_page,aboutus_page,
    contactus_page,
    LandingPageView,
    SignupView,
    dashboard,
    DashboardView,DownloadLeadsView,UploadCSVView,MatchFieldsView,ProcessDataView,
    # CreateNotificationView, MarkAsReadView, ClearNotificationsView,create_lead_notification
 )
from campaign.views import ContactView
from fb_app.views import fb_callback,fb_test
# from whatsapp.views import whatsapp_callback





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',landing_page , name="landing-page"),
    path('fb_callback/',fb_callback , name="fb_callback"),
    path('fb_login/',fb_test , name="fb_login"),
    # path('whatsapp_callback/',whatsapp_callback , name="whatsapp_callback")
    # path('pricing/',pricing_page , name="pricing-page"),
    path('services/',services_page , name="services-page"),
    path('aboutus/',aboutus_page , name="aboutus-page"),
    # path('setting/',setting_page , name="setting-page"),
    # path('contactus/',contactus_page , name="contactus-page"),
    path('contactus/',ContactView.as_view() , name="contactus-page"),
    path('dashboard/',DashboardView.as_view() , name="dashboard"),
    # path('',LandingPageView.as_view() , name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    # path('membership/', include('membership.urls',namespace="membership")),
    path('campaigns/', include('campaign.urls',namespace="campaigns")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('reset-password/', PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name="password_reset_comfirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    # path('contact/',ContactUsView.as_view(), name='contact')
    path('download/', DownloadLeadsView.as_view(), name='download_leads'),
    # path('upload/', UploadCSVView.as_view(), name='upload'),
    path('upload/', UploadCSVView.as_view(), name='upload'),
    path('match-fields/', MatchFieldsView.as_view(), name='match-fields'),
    path('process-data/', ProcessDataView.as_view(), name='process-data'),
    # path('notifications/create/', CreateNotificationView.as_view(), name='create_notification'),
    # path('notifications/create/', create_lead_notification, name='create_notification'),
    # path('notifications/mark-as-read/<int:notification_id>/', MarkAsReadView.as_view(), name='mark_as_read'),
    # path('notifications/clear/', ClearNotificationsView.as_view(), name='clear_notifications'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#considering production
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from leads.models import Agent,UserProfile

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    role = forms.ChoiceField(choices=Agent.ROLE_CHOICES)

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name', 
            'role', 
        )

   

agents/views.py
import random
from django.shortcuts import render
from django.core.mail import send_mail
from django.views import generic
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganiserAndLoginRequiredMixin
from leads.models import Campaign
from django.http import Http404
from django.core.mail import EmailMessage
from django.views import generic
# from .models import Agent, Campaign

class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        organisation = self.request.user.userprofile
        agents = Agent.objects.filter(organisation=organisation)
        agent_data = []

        for agent in agents:
            # Get the campaigns associated with the current agent
            campaigns = Campaign.objects.filter(agent=agent)

            # Add agent's email, role, and campaigns to the agent_data list
            agent_data.append({
                'agent': agent,
                'role': agent.get_role_display(),  # Get the display value of the role
                'campaigns': campaigns,
            })

        context['agent_data'] = agent_data
        return context





class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm
    
    # print("Success! Agent created and email sent.")


    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self,form):
        user = form.save(commit=False)
        print(form.cleaned_data['role'])
        user.is_agent = True
        user.is_organiser = False
        user.set_password(f"{random.randint(0,10000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            role=form.cleaned_data['role'],
            organisation = self.request.user.userprofile
        )
                # Send email to the user using smtp
        subject = 'You are added to Kybic CRM'
        body = 'You are added to kybic CRM as a staff'
        from_email = 'developer.addox@gmail.com'
        to_email = [user.email]
        email = EmailMessage(subject, body, from_email, to_email)
        email.send()

        # agent.organisation = self.request.user.userprofile
        # agent.save()
        # print("Success! Agent created and email sent.")
        return super(AgentCreateView,self).form_valid(form)






# class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
#     template_name = "agents/agent_detail.html"
#     context_object_name = "agent"

#     def get_queryset(self):
#         organisation = self.request.user.userprofile
#         return Agent.objects.filter(organisation = organisation)

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         agent = self.get_object()
#         campaigns = Campaign.objects.filter(agent=agent)
#         context['campaigns'] = campaigns
#         return context

class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agent = self.get_object()
        campaigns = Campaign.objects.filter(agent=agent)
        context['campaigns'] = campaigns
        return context


class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)

    def get_object(self, queryset=None):
        # Get the specific Agent object you want to update
        obj = super().get_object(queryset=queryset)
        return obj
    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['user'] = self.request.user
    #     return kwargs   



class AgentDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)   

agents/templates/agents/agent_create.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>


    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
    <div>
    <h1 class="h1">Create a New Staff</h1>
        <button class="button" style="margin:10px 0 50px auto;">
                <a href="{% url 'agents:agent-list' %}">Go back to Staff Section</a>
        </button>
    </div>

        <form method="post">
            {%csrf_token%}
            {{form|crispy}}

            <button type="submit" class="button">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

agents/templates/agents/agent_delete.html
     





{% extends "main.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}    
    <style>
     section{
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;
        }
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;
    
      }
      .button a{
        color: aliceblue;
    
      }
    </style>
    
    <!-- Content -->
    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->

            
            <section class=" flex mt-20 items-center">
                    <h1>Are you sure you want to delete this Agent</h1>
                    <div>
                        <form method="post">
                            {%csrf_token%}
                            {{form|crispy}}
                            <button type="submit" class="button text-black mt-5 mx-auto">Delete</button>
                        </form>
                    
                    </div>
                    <button class="button my-5 mx-auto">
                            <a href="{% url 'agents:agent-list' %}">Go back to Agents</a>   
                    </button>
            </section>
         
                     
      </div>
    <!-- End of content -->
    
    
    </div>
    
    
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}>
    
    </script>
    
    
    
      
    {% endblock content %}
    
    
    
    
    
        
      
       

agents/templates/agents/agent_detail.html
    {% extends "main.html" %}
    {% load static %}
    {% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;
    
      }
      .button a{
        color: aliceblue;
    
      }
    </style>    
    <!-- Content -->
    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->

            <section class="flex flex-col justify-center flex-wrap items-center">
              <div class="container px-5 py-10 mx-auto">
              <div class="basic flex flex-row flex-wrap">
                <div class="icon w-20 h-20 p-0 border rounded-full mr-10">
                    <img src="{% static 'images/user1.jpg' %}" alt="" class="w-20 h-20 rounded-full">
                </div>
                <div class="text-main flex flex-col">
                  <h3>{{agent.user.username}}</h3>
                  <p>ID: {{agent.user.id}}</p>
                  <p>Email: {{agent.user.email}}</p>
                  {% comment %} <p>Email: {{agent.user.password}}</p> {% endcomment %}
                  <p>Role: {{agent.role}}</p>
                  <p>Created: {{agent.user.date_joined}}</p>
      
                  <div class="buttons flex flex-row justify-start gap-5 mt-5 flex-wrap">
                      {% comment %}  <a href="tel:+{{}}">
                        <button class="button">
                          <i class="bx bxs-phone-call"></i>
                          Call
                        </button>
                      </a>  
                      <a href="mailto:{{agent.user.email}}">
                        <button class="button">
                          <i class="bx bxs-send"></i>
                          Email
                        </button>
                      </a>
                      {% endcomment %}
                      <a href="{% url 'agents:agent-update' agent.pk %}"  class="">
                        <button class="button">Update Details</button>
                      </a>
                      <a href="{% url 'agents:agent-delete' agent.pk %}"  class="">
                        <button class="button">Remove</button>
                      </a>
      
                  </div>
                </div>
              </div>
              <hr class="mt-5">
              <div class="detailed">
              {% comment %} {% if campaigns_exist %} {% endcomment %}
              
{% if campaigns.exists %}
<div class="bg-white py-0 sm:py-0">
 <h1 class="mt-5 mx-auto text-xl font-bold border-b  sm:text-xl ">Assigned Campigns</h1>
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto mt-2 grid max-w-2xl grid-cols-1 gap-y-16 gap-x-8  pt-10   lg:mx-0 lg:max-w-none lg:grid-cols-3">
      {% for campaign in campaigns %}  
      
      <article class=" campaign-item flex max-w-xs flex-col items-start justify-between drop-shadow border border-dotted rounded-2xl px-3 py-3 border-black-800 max-w-xs   hover:border-solid" style="max-width:280px">
      {% comment %} <article class="flex max-w-xl flex-col items-start justify-between"> {% endcomment %}
        <div class="flex items-center gap-x-4 text-xs">
          <time datetime="2020-03-16" class="text-gray-500"> Start: {{campaign.start_date}}</time>
          <time datetime="2020-03-16" class="text-gray-500"> End: {{campaign.end_date}}</time>
        </div>
        <div class="group relative">
          <h3 class="mt-3 text-lg font-semibold leading-6 text-gray-900 uppercase group-hover:text-gray-600">
            <a href="#">
              <span class="absolute inset-0 "></span>
              {{campaign.name}}
            </a>
          </h3>
          <p class="mt-5 text-sm leading-6 text-gray-600 line-clamp-3">
            Goal of the campaign: {{campaign.description}}
          </p>
        </div>
        
        
        <div>
            <a href="{% url 'campaigns:campaign-detail' campaign.pk %}">
              <button class="button mt-5"> View More</button>
            </a>
        </div> 
      </article>
      {% endfor %}
    </div>
  </div>
</div>
{% else %}
<p>No campaign is assigned</p>
{% endif %} 
              {% comment %} {% else %} {% endcomment %}
                
              {% comment %} {% endif %} {% endcomment %}
              </div>
             
              </div>
              
          </section>
    
         
                     
      </div>
    <!-- End of content -->
    
    
    </div>
    
    
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}>
    
    </script>
    
    
    
      
    {% endblock content %}
    
    
    
    
    
        
      

agents/templates/agents/agent_list.html
{% extends "main.html" %}
{% load static %}



{% block content %}
<!-- <nav>
    <div class="company-logo">
        <img src="{% static 'images/logo1.png' %}" alt="Kybic">
    </div>

</nav> -->



<style>
  .button{
    min-width: 100px;
    padding: 7px 20px;
    background: rgb(1, 12, 22);
    border-radius: 20px;
    box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
    color: aliceblue;

  }
  .button a{
    color: aliceblue;

  }
</style><!-- Content -->

  <div class="sub-container "> 
        <!-- # Total staff Session -->

      <div class="bg-transparent px-5 py-10 md:py-32" style="padding: 10px;">
        <div class="mx-auto flex  flex-col   gap-y-20 items-start gap-x-8 px-auto md:px-16 ">
          <div class=" flex flex-row flex-wrap justify-between w-full items-end border-b border-gray-200" style="gap:20%">
            <h2 class="text-3xl  font-bold tracking-tight text-gray-900 sm:text-4xl">Staff List</h2>
            <div>
                {% if request.user.is_organiser %}
                    <a href="{% url 'agents:agent-create' %}" class="text-gray-500 hover:text-blue-500">
                      <button class="flex flex-col items-center justify-center ">
                        <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                          <img src="{% static 'images/addstaff.png' %}"  alt="" class="w-6 ">
                        </div>
                        <p class="text-gray-700 text-sm mt-2 "> New Staff</p>
                      </button>
                    </a>
                  </button>
                {% endif %}
              </div>
          </div>
          <ul role="list" class=" flex flex-row flex-wrap gap-3 md:gap-10 "> 
              {% for agent in object_list %}            
                  <li class=" " style="width: 150px;">
                    <a href="{% url 'agents:agent-detail' agent.pk %}">
                      <div class=" staff-badge flex flex-col items-center gap-3 shadow p-3 rounded-xl border hover:bg-indigo-100" >
                        <img class="h-10 w-10 rounded-full border" src="{% static 'images/user1.jpg' %}" alt="">
                        <div>
                          <h3 class="text-center font-semibold leading-7 tracking-tight text-gray-900">{{agent.user.username}}</h3>
                          <!-- <p class="text-sm font-semibold leading-6 text-indigo-600">{{agent.user.email}}</p> -->
                          <p class="text-sm font-semibold leading-6 text-indigo-600">{{agent.role}}</p>
                        </div>
                      </div>
                    </a>
                   
                  </li>
              {% endfor %}
          </ul>
        </div>
      </div>
  
      <section class="">
        <div class="sub-cont overflow-x-scroll md:ml-8" style="margin: 5px; max-width: none;">      
            <h2 class="mb-10 font-bold text-2xl md:text-4xl" style=" margin: auto; margin-bottom: 10px;text-align: center;font-size: 1.6rem;"></h2>
            <!-- <p>This is the follow up leads section.</p> -->
            <table id="example1" class="lead-list stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
              <thead>
                <tr>
                  <!-- <th data-priority="1">Name</th> -->
                  <th data-priority="1">Staff Name</th>
                  <th data-priority="1">Role</th>
                  <th data-priority="2">Campaigns</th>
                  
                  <!-- <th data-priority="1">Name</th> -->
                </tr>
              </thead>
                 <tbody>
                  {% for agent_data in agent_data %}
                    <tr>
                        <td>{{agent_data.agent.user.username}}</td>
                        <td>{{agent_data.agent.role}}</td>
                        <td>
                          <div class="" style="display: flex; flex-wrap: wrap; gap: 15px;">
                          {% for campaign in agent_data.campaigns %}
                          <p>{{ campaign.name }}</p>
                          {% endfor %}
                        </div>
                        </td>
                    </tr>
                {% endfor %}                     
              </tbody>
            </table>
        </div>

        

      </section>
    
  </div>
<!-- End of content -->


</div>


<!-- JS File -->
<script type="text/javascript" src={% static 'js/main.js' %}></script>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> 
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script> 
<script>
  $(document).ready(function() {

      // var table = $('#exampletot').DataTable({
      // 	responsive: true
      // })
      var table = $('#example1').DataTable({
        responsive: true
      })
      var table = $('#example2').DataTable({
        responsive: true
      })
      var table = $('#example3').DataTable({
        responsive: true
      })
      var table = $('#example4').DataTable({
        responsive: true
      })
      
  });    
</script> 



  
{% endblock content %}





    
  
   

agents/templates/agents/agent_update.html
{% extends "main.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;
    
      }
      .button a{
        color: aliceblue;
    
      }
    </style>
     
    <!-- Content -->
    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->

            <section class="text-gray-600 body-font overflow-scroll">
              <div class="container px-5 py-24 mx-auto">
                <div class="lg:w-4/5 mx-auto flex flex-wrap">
                  <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
                    <div class="flex mb-4 justify-around ">
                      <a href=" {% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        <button class="button">
                          Go Back
                        </button>
                      </a>
                    </div>
                    
                        <form method="post">
                            {%csrf_token%}
                            {{form|crispy}}
                            <button type="submit" class="button">Submit</button>
                        </form>       
                  </div>
                </div>
              </div>
            </section> 
    
         
                     
      </div>
    <!-- End of content -->
    
    
    </div>
    
    
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}>
    
    </script>
    
    
    
      
    {% endblock content %}
    
    
    
    
    
        
      
       