campaign/urls.py
from django.urls import path
from .views import CampaignListView,CampaignCreateView,CampaignDetailView,CampaignUpdateView,CampaignDeleteView,AssignAgentView,CampaignAddAgentView


app_name = 'campaign'

urlpatterns = [
    path('',CampaignListView.as_view(), name='campaign-list'),
    path('<int:pk>/' , CampaignDetailView.as_view(),name='campaign-detail'),
    path('<int:pk>/update/',CampaignUpdateView.as_view(), name='campaign-update'),
    path('<int:pk>/delete/',CampaignDeleteView.as_view(), name='campaign-delete'),
    path('create/',CampaignCreateView.as_view(), name='campaign-create'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path("campaign/<int:pk>/add-agent/", CampaignAddAgentView.as_view(), name="campaign-add-agent"),
    




]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

    )
from django.urls import path, include
from leads.views import (
    landing_page,pricing_page,
    services_page,aboutus_page,
    contactus_page,
    LandingPageView,
    SignupView,
    dashboard,
    DashboardView,DownloadLeadsView,UploadCSVView,MatchFieldsView,ProcessDataView,
    # CreateNotificationView, MarkAsReadView, ClearNotificationsView,create_lead_notification
 )
from campaign.views import ContactView
from fb_app.views import fb_callback,fb_test
# from whatsapp.views import whatsapp_callback





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',landing_page , name="landing-page"),
    path('fb_callback/',fb_callback , name="fb_callback"),
    path('fb_login/',fb_test , name="fb_login"),
    # path('whatsapp_callback/',whatsapp_callback , name="whatsapp_callback")
    # path('pricing/',pricing_page , name="pricing-page"),
    path('services/',services_page , name="services-page"),
    path('aboutus/',aboutus_page , name="aboutus-page"),
    # path('setting/',setting_page , name="setting-page"),
    # path('contactus/',contactus_page , name="contactus-page"),
    path('contactus/',ContactView.as_view() , name="contactus-page"),
    path('dashboard/',DashboardView.as_view() , name="dashboard"),
    # path('',LandingPageView.as_view() , name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    # path('membership/', include('membership.urls',namespace="membership")),
    path('campaigns/', include('campaign.urls',namespace="campaigns")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('reset-password/', PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name="password_reset_comfirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    # path('contact/',ContactUsView.as_view(), name='contact')
    path('download/', DownloadLeadsView.as_view(), name='download_leads'),
    # path('upload/', UploadCSVView.as_view(), name='upload'),
    path('upload/', UploadCSVView.as_view(), name='upload'),
    path('match-fields/', MatchFieldsView.as_view(), name='match-fields'),
    path('process-data/', ProcessDataView.as_view(), name='process-data'),
    # path('notifications/create/', CreateNotificationView.as_view(), name='create_notification'),
    # path('notifications/create/', create_lead_notification, name='create_notification'),
    # path('notifications/mark-as-read/<int:notification_id>/', MarkAsReadView.as_view(), name='mark_as_read'),
    # path('notifications/clear/', ClearNotificationsView.as_view(), name='clear_notifications'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#considering production
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls  import path
from .views import (
    lead_list,lead_detail,lead_update,lead_delete,
    LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView,CategoryListView,
    # CategoryDetailView,CategoryCreateView,CategoryUpdateView,CategoryDeleteView,
    LeadCategoryUpdateView,
    FollowUpCreateView,FollowUpUpdateView, FollowUpDeleteView,FollowUpListView,DownloadLeadsView,SettingsPageView,
    # WhatsappMessagingView,
    lead_form_submissions,
    )
from django.conf.urls import handler404,handler400,handler403,handler500
from leads.views import error_404,error_400,error_403,error_500,error_401,error_405
# from campaign.views import AssignAgentView

handler404 = error_404
handler400 = error_400
handler403 = error_403
handler401 = error_401
handler405 = error_405
handler500 = error_500


app_name = "leads"

urlpatterns = [
    path('',LeadListView.as_view(),name="lead-list"),
    path('facebook/',lead_form_submissions,name="facebook-lead-list"),
    # path('<int:campaign_id>/<int:pk>/',LeadDetailView.as_view(),name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/update/', LeadUpdateView.as_view(),name="lead-update"),
    path('<int:campaign_id>/<int:pk>/delete/', LeadDeleteView.as_view(),name="lead-delete"),
    # path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path('<int:campaign_id>/<int:pk>/category/', LeadCategoryUpdateView.as_view(),name="lead-category-update"),
    path('leads/followups/', FollowUpListView.as_view(), name='followup-list'), 
    path('settings', SettingsPageView.as_view(), name='settings'), 
    # path('<int:campaign_id>/followups/', FollowUpView.as_view(), name='followup-leads'),
    path('<int:campaign_id>/<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),    
    path('followups/<int:campaign_id>/<int:pk>/update/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('<int:pk>/create/', LeadCreateView.as_view(),name="lead-create"),
    # path('<int:pk>/whatsapp/', WhatsappMessagingView.as_view(), name='lead-whatsapp'),
    # path('create-category/', CategoryCreateView.as_view(),name="category-create"),
    path('categories/' , CategoryListView.as_view(), name="category-list"),
    # path('categories/<int:pk>/update/' ,CategoryUpdateView.as_view(), name="category-update"),
    # path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(),name="category-delete"),
    # path('categories/' , CategoryDetailView.as_view(), name="category-detail"),
    # path('upload/', UploadFileView.as_view(), name='upload'),


]

campaign/models.py
from django.db import models

# Create your models here.

campaign/views.py
import random
from django.db.models import OuterRef, Subquery, Count
from django.shortcuts import render
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.views import generic
from django.shortcuts import reverse,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Campaign
from leads.models import Agent
from .mixins import OrganiserAndLoginRequiredMixin
from .forms import CampaignModelForm,CampaignAddAgentModelForm,ContactForm
from leads.forms import AssignAgentForm
from leads.views import Lead
from django.core.mail import EmailMessage
from django.urls import reverse
from django.http import HttpResponse


class CampaignListView(LoginRequiredMixin,generic.ListView):
    template_name = "campaigns/campaign_list.html"
    context_object_name = "campaigns"

    def get_queryset(self):
        user = self.request.user
        
        #inistial query set for the entireorganisation
        if user.is_organiser:
            campaigns = Campaign.objects.filter(organisation=user.userprofile) 
            queryset =campaigns
            print(queryset)
        else: 
            queryset = Campaign.objects.filter(
                organisation = user.agent.organisation,
                agent__isnull = False
            ) 

            # query set for the agent logged in
            queryset = queryset.filter(agent__user = user)
                # Add a subquery to count the total number of leads for each campaign
        subquery = Lead.objects.filter(campaign=OuterRef('pk')).order_by().values('campaign__id').annotate(count=Count('*')).values('count')
        queryset = queryset.annotate(total_leads=Subquery(subquery))

        return queryset.distinct()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get all the campaigns
        all_campaigns = self.get_queryset()

        # Get the last four campaigns
        last_four_campaigns = all_campaigns[:4]

        # Store all the campaigns and last four campaigns in the context
        context['all_campaigns'] = all_campaigns
        context['last_four_campaigns'] = last_four_campaigns

        return context
   
  
# Create Campaignshere.


# class CampaignCreateView(OrganiserAndLoginRequiredMixin,generic.CreateView):
#     template_name = "campaigns/campaign_create.html"
#     form_class = CampaignModelForm

#     def get_success_url(self):
#         return reverse("campaign:campaign-list")

#     def form_valid(self,form):
#         campaign = form.save(commit=False)
#         organisation = self.request.user.userprofile
#         campaign.organisation = organisation
#         campaign.save()
#         # send mail
#         send_mail(
#             subject="A campaign has been created",
#             message="Go to the site to see the lead",
#             from_email="test@test.com",
#             recipient_list=["test2@test.com"],
#         )
#         return super(CampaignCreateView,self).form_valid(form)


# class CampaignCreateView(OrganiserAndLoginRequiredMixin,generic.CreateView):
#     template_name = "campaigns/campaign_create.html"
#     form_class = CampaignModelForm

#     def get_success_url(self):
#         return reverse("campaign:campaign-list")

#     def form_valid(self,form):
#         campaign = form.save(commit=False)
#         organisation = self.request.user.userprofile
#         campaign.organisation = organisation
#         campaign.save()
#         # send mail
#         send_mail(
#             subject="A campaign has been created",
#             message="Go to the site to see the lead",
#             from_email="test@test.com",
#             recipient_list=["test2@test.com"],
#         )
#         return super(CampaignCreateView,self).form_valid(form)

#     def get_form_kwargs(self):
#         kwargs = super().get_form_kwargs()
#         kwargs['user'] = self.request.user
#         return kwargs
class CampaignCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "campaigns/campaign_create.html"
    form_class = CampaignModelForm
    print("campaign create view")

    def get_success_url(self):
        return reverse("campaign:campaign-list")

    def form_valid(self, form):
        print("hi")
        campaign = form.save(commit=False)
        organisation = self.request.user.userprofile
        campaign.organisation = organisation
        campaign.save()

        # Add agents to the campaign
        agents = form.cleaned_data['agents']
        campaign.agent.set(agents)
        print("hiooo")
        for agent in agents:
            #send mail
            #Send email to the user using smtp
            subject = 'New Campaign assigned to you.'
            body = 'A new campaign assigned to you by the admin, please visit the www.crm.addox.in to check it.'
            from_email = 'developer.addox@gmail.com'
            to_email = [agent.user.email]
            email = EmailMessage(subject, body, from_email, to_email)
            email.send()

        
        return super(CampaignCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class CampaignUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = "campaigns/campaign_update.html"
    form_class = CampaignModelForm

    def get_success_url(self):
        return reverse("campaigns:campaign-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Campaign.objects.filter(organisation=organisation)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs



class CampaignDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'campaigns/campaign_detail.html'
    model = Campaign
    context_object_name = 'campaign'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        campaign = context['campaign']
        leads = campaign.leads.all()

        lead_followups = {}
        for lead in leads:
            followups = lead.followups.all()
            if followups.exists():
                lead_followups[lead.id] = followups.latest('date_added')
            else:
                lead_followups[lead.id] = None

        context['leads'] = leads
        context['lead_followups'] = lead_followups

        return context



class CampaignDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = "campaigns/campaign_delete.html"
    context_object_name = "campaign"

    def get_success_url(self):
        return reverse("campaigns:campaign-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Campaign.objects.filter(organisation = organisation)   


class CampaignAddAgentView(OrganiserAndLoginRequiredMixin, generic.FormView):
    template_name = "campaigns/campaign_add_agent.html"
    form_class = CampaignAddAgentModelForm

    
    def dispatch(self, request, *args, **kwargs):
        self.campaign_id = kwargs['pk']
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['campaign_id'] = self.campaign_id
        return kwargs
    def get_success_url(self):
        return reverse("campaign:campaign-detail", kwargs={"pk": self.campaign_id})

    def form_valid(self, form):
        campaign = Campaign.objects.get(id=self.campaign_id)
        agents = form.cleaned_data['agent']
        
        for agent in agents:
            campaign.agent.add(agent)
            subject = 'New Campaign assigned to you.'
            body = 'A new campaign assigned to you by the admin, please visit the www.crm.addox.in to check it.'
            from_email = 'developer.addox@gmail.com'
            to_email = [agent.user.email]
            email = EmailMessage(subject, body, from_email, to_email)
            email.send()
        messages.success(self.request, "Agents added successfully.")
        return super().form_valid(form)

class AssignAgentView(OrganiserAndLoginRequiredMixin, generic.FormView):
    template_name = "campaigns/assign_agent.html"
    form_class = AssignAgentForm


    
    def get_form_kwargs(self,**kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update( {
            "request":self.request
        })
        return kwargs

        
    def get_success_url(self):
        return reverse("campaign:campaign-list")
    
    def form_valid(self, form):
        agent=form.cleaned_data["agent"]
        campaign = Campaign.objects.get(id=self.kwargs["pk"])
        print(campaign)
        campaign.agent = agent
        campaign.save()
        return super(AssignAgentView, self).form_valid(form)




# send mail 
# views.py

from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import FormView

from .forms import ContactForm

class ContactView(FormView):
    template_name = 'contactus.html'
    form_class = ContactForm
    success_url = reverse_lazy('contactus-page')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']

        # Build the message
        # template = get_template('email/contact.txt')
        context = {
            'name': name,
            'email': email,
            'phone': phone,
            'subject': subject,
            'message': message,
        }

campaign/templates/campaigns/add_agents_to_campaign.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>


    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
      <div>
        <button class="button" style="margin:10px 0 50px auto;">
            <a href="{% url 'campaigns:campaign-list' %}" >Go back to campaigns</a>
        </button>
    </div>

   

    <hr>
    <h1>Assign an agent to this campaign</h1>


    <form method="post">
        {%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="button"  >Submit</button>
    </form>

</div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

campaign/templates/campaigns/assign_agent.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>



    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
      <div>
        <button class="button" style="margin:10px 0 50px auto;">
            <a href="{% url 'campaigns:campaign-list' %}" >Go back to campaigns</a>
        </button>
    </div>

   

    <hr>
    <h1>Assign an agent to this campaign</h1>


    <form method="post">
        {%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="button"  >Submit</button>
    </form>

</div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

campaign/templates/campaigns/campaign_create.html
{% extends "main.html" %}

{% load tailwind_filters %}
{% load static %}

    {% block content %}
    <style>
        form{
            width: 95vw;
            margin: auto;
            max-width: 500px;
        }
        .button{
            min-width: 100px;
            padding: 7px 20px;
            background: rgb(1, 12, 22);
            border-radius: 20px;
            box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
            color: aliceblue;

        }
        .button a{
            color: aliceblue;

        }
        .h1{
            text-align: center;
            font-size: 1.3rem;
            font-weight: 700;
        }
    </style>

    <div class="sub-container">

     
        <div class="total-count">

   
 

<div class="form mx-auto">
    <div>
    <h1 class="h1">Create a New Campaign</h1>
        <button class="button" style="margin:10px 0 50px auto;">
                <a href="{% url 'campaigns:campaign-list' %}">Go back to Campaign Section</a>
        </button>
    </div>

        <form method="post">
            {%csrf_token%}
            {{form|crispy}}

            <button type="submit" class="button">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script type="text/javascript" src={% static 'js/main.js' %}></script>

     {% endblock content %}

campaign/templates/campaigns/campaign_detail.html
    {% extends "main.html" %}
    {% load static %}
    {% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;
    
      }
      .button a{
        color: aliceblue;
    
      }
    </style>

    
    <!-- Content -->
    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->

            <section class="flex flex-col justify-center flex-wrap items-center">
              <div class="container px-5 py-10 mx-auto">
              <div class="basic flex flex-row flex-wrap">
                <div class="icon   p-0  " >
                    <img src="{% static 'images/campaign-icon.png' %}" alt="" class="h-25 " style="height:180px">
                </div>
                <div class="text-main flex flex-col items-start">
                  <h3 class="text-2xl capitalize font-bold">{{campaign.name}}</h3>
                  <p>End Date: {{campaign.end_date}}</p>
                  <p>Ad ID: {{campaign.ad_id}}</p>
                  <p class=" flex flex-row flex-wrap justify-center  my-3">Assigned to:
                  <div class=" text-gray-900  flex flex-row flex-wrap gap-2">
                      {% for agent in campaign.agent.all %}      
                       <p class=" staff-badge rounded-xl  shadow px-3 text-center text-sm mb-2" style="min-width:50px">{{ agent.user.username }}</p>
                      {% endfor %}
                  </div>
                  </p>
                  {% comment %} <p>Email: {{agent.user.password}}</p> {% endcomment %}
                  {% comment %} <p>Role: {{agent.user.role}}</p>
                  <p>Created: {{agent.user.date_joined}}</p>
       {% endcomment %}
                  <div class="buttons flex flex-row justify-start gap-5 mt-5 flex-wrap">
                       {% if request.user.is_organiser  %} 
                      <a href="{% url 'campaigns:campaign-update' campaign.pk %}"  class="">
                        <button class="flex flex-col items-center justify-center ">
                            <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                              <img src="{% static 'images/update.png' %}"  alt="" class="w-6 ">
                            </div>
                            <p class="text-gray-700 text-sm mt-2 "> Update</p>
                        </button>
                      </a>
                                               
                        <a href="{% url 'leads:lead-create' campaign.pk %}" class="text-gray-500 hover:text-blue-100 ">                      
                          <button class="flex flex-col items-center justify-center ">
                                <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                                  <img src="{% static 'images/newlead.png' %}"  alt="" class="w-6 ">
                                </div>
                                <p class="text-gray-700 text-sm mt-2 "> Add lead</p>
                          </button>
                        </a>  
                        {% if user.is_organiser %}
                          <a href="{% url 'campaign:campaign-add-agent' object.id %}">
                            <button class="flex flex-col items-center justify-center ">
                            <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                              <img src="{% static 'images/addstaff.png' %}"  alt="" class="w-6 ">
                            </div>
                            <p class="text-gray-700 text-sm mt-2 "> Add Staff</p>
                            </button>
                          </a>
                          
                        {% endif %}
                        <a href="{% url 'campaigns:campaign-delete' campaign.pk %}"  class="">
                          <button class="flex flex-col items-center justify-center ">
                            <div class="p-2.5 bg-blue-100 rounded-full shadow hover:shadow-xl">
                              <img src="{% static 'images/remove.png' %}"  alt="" class="w-6 ">
                            </div>
                            <p class="text-gray-700 text-sm mt-2 ">Remove</p>
                          </button>
                        </a> 

                      {% endif %}
                      
      
                  </div>
                </div>
              </div>
              <hr class="mt-5">
              <div>
             
               </div>
              <div class="detailed">
                {% comment %} <h1 class="mt-5 text-3xl font-bold">Leads</h1><hr width="120px">
{% if request.user.is_organiser %}
                <div class="border-b ">                 
                    <button class=" my-3">
                                    
                    </button>
                 
                </div>
  {% endif %}
   {% endcomment %}


  {% if leads.exists %}    
        <div class="container w-full   mx-auto px-2 ">
            <!--Title-->
            <h1 class="flex items-center  font-bold break-normal  px-3 mt-20 pt-8 text-xl md:text-2xl">
              Leads under the campaign

            </h1>
              <!--Card-->
              <div id='recipients' class="p-3 mt-0 lg:mt-0 rounded w-full bg-white">
                <table id="example" class="lead-list stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                  <thead>
                    <tr>
                      <th data-priority="1">Name</th>
                      <th data-priority="2">Status</th>
                      <th data-priority="3">Date Added</th>
                      {% comment %} <th data-priority="4">More</th> {% endcomment %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for lead in leads%}                            
                        <tr>
                          <td>
                            <a href="{% url 'leads:lead-detail' campaign_id=campaign.id pk=lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                              {{lead.first_name}}
                            </a>
                          </td>
                          <td>{{lead.category}}</td>
                          <td>{{lead.date_added}}</td>
                          {% comment %} <td>
                            <a href="{% url 'leads:lead-detail' campaign_id=campaign.id pk=lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                              View More
                            </a>
                          </td> {% endcomment %}
                        </tr>                           
                    {% endfor %}
                  </tbody>
                </table>
              </div><!--/Card-->
        </div>
    
  {% else %}
      <p class="mx-auto mb-5">sorry , There is no leads assigned for you right now.</p>
      <a href="{% url 'dashboard' %}"><button class="button">Go back  </button></a>
  {%endif%}

                </div>
                </div>
      
              </div>
              <hr class="mt-10">
              </div>
              
          </section>
    
         
                     
      </div>
    <!-- End of content -->
    
    
    </div>
    
    
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

	<!--Datatables -->
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script>
		$(document).ready(function() {

			var table = $('#example').DataTable({
					responsive: true
				})
				.columns.adjust()
				.responsive.recalc();
		});
	</script>
    
    
      
    {% endblock content %}
    

    
    
        
      
       

campaign/templates/campaigns/campaign_update.html
{% extends "main.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}    
    <style>
      .button{
        min-width: 100px;
        padding: 7px 20px;
        background: rgb(1, 12, 22);
        border-radius: 20px;
        box-shadow: 1px 3px 9px 4px rgba(0, 0, 0, 0.184);
        color: aliceblue;
    
      }
      .button a{
        color: aliceblue;
    
      }
    </style>

    
    <!-- Content -->
    
      <div class="sub-container "> 
            <!-- # staff Detailed Session -->

            <section class="text-gray-600 body-font overflow-scroll">
              <div class="container px-5 py-24 mx-auto">
                <div class="lg:w-4/5 mx-auto flex flex-wrap">
                  <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">Campaign</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{campaign.name}} </h1>
                    <div class="flex mb-4 justify-around ">
                      <a href=" {% url 'campaigns:campaign-detail' campaign.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        <button class="button">
                          Go Back
                        </button>
                      </a>
                    </div>
                    
                        <form method="post">
                            {%csrf_token%}
                            {{form|crispy}}
                            <button type="submit" class="button">Submit</button>
                        </form>       
                  </div>
                </div>
              </div>
            </section> 
    
         
                     
      </div>
    <!-- End of content -->
    
    
    </div>
    
    
    <!-- JS File -->
    <script type="text/javascript" src={% static 'js/main.js' %}>
    
    </script>
    
    
    
      
    {% endblock content %}
    
    
    
    
    
        
      
       