agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name = 'agents'


urlpatterns = [
    path('',AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/' , AgentDetailView.as_view(),name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),
    path('create/',AgentCreateView.as_view(), name='agent-create'),


]

campaign/urls.py
from django.urls import path
from .views import CampaignListView,CampaignCreateView,CampaignDetailView,CampaignUpdateView,CampaignDeleteView,AssignAgentView,CampaignAddAgentView


app_name = 'campaign'

urlpatterns = [
    path('',CampaignListView.as_view(), name='campaign-list'),
    path('<int:pk>/' , CampaignDetailView.as_view(),name='campaign-detail'),
    path('<int:pk>/update/',CampaignUpdateView.as_view(), name='campaign-update'),
    path('<int:pk>/delete/',CampaignDeleteView.as_view(), name='campaign-delete'),
    path('create/',CampaignCreateView.as_view(), name='campaign-create'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path("campaign/<int:pk>/add-agent/", CampaignAddAgentView.as_view(), name="campaign-add-agent"),
    




]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

    )
from django.urls import path, include
from leads.views import (
    landing_page,pricing_page,
    services_page,aboutus_page,
    contactus_page,
    LandingPageView,
    SignupView,
    dashboard,
    DashboardView,DownloadLeadsView,UploadCSVView,MatchFieldsView,ProcessDataView,
    # CreateNotificationView, MarkAsReadView, ClearNotificationsView,create_lead_notification
 )
from campaign.views import ContactView
from fb_app.views import fb_callback,fb_test
# from whatsapp.views import whatsapp_callback





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',landing_page , name="landing-page"),
    path('fb_callback/',fb_callback , name="fb_callback"),
    path('fb_login/',fb_test , name="fb_login"),
    # path('whatsapp_callback/',whatsapp_callback , name="whatsapp_callback")
    # path('pricing/',pricing_page , name="pricing-page"),
    path('services/',services_page , name="services-page"),
    path('aboutus/',aboutus_page , name="aboutus-page"),
    # path('setting/',setting_page , name="setting-page"),
    # path('contactus/',contactus_page , name="contactus-page"),
    path('contactus/',ContactView.as_view() , name="contactus-page"),
    path('dashboard/',DashboardView.as_view() , name="dashboard"),
    # path('',LandingPageView.as_view() , name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    # path('membership/', include('membership.urls',namespace="membership")),
    path('campaigns/', include('campaign.urls',namespace="campaigns")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('reset-password/', PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name="password_reset_comfirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    # path('contact/',ContactUsView.as_view(), name='contact')
    path('download/', DownloadLeadsView.as_view(), name='download_leads'),
    # path('upload/', UploadCSVView.as_view(), name='upload'),
    path('upload/', UploadCSVView.as_view(), name='upload'),
    path('match-fields/', MatchFieldsView.as_view(), name='match-fields'),
    path('process-data/', ProcessDataView.as_view(), name='process-data'),
    # path('notifications/create/', CreateNotificationView.as_view(), name='create_notification'),
    # path('notifications/create/', create_lead_notification, name='create_notification'),
    # path('notifications/mark-as-read/<int:notification_id>/', MarkAsReadView.as_view(), name='mark_as_read'),
    # path('notifications/clear/', ClearNotificationsView.as_view(), name='clear_notifications'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#considering production
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls  import path
from .views import (
    lead_list,lead_detail,lead_update,lead_delete,
    LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView,CategoryListView,
    # CategoryDetailView,CategoryCreateView,CategoryUpdateView,CategoryDeleteView,
    LeadCategoryUpdateView,
    FollowUpCreateView,FollowUpUpdateView, FollowUpDeleteView,FollowUpListView,DownloadLeadsView,SettingsPageView,
    # WhatsappMessagingView,
    lead_form_submissions,
    )
from django.conf.urls import handler404,handler400,handler403,handler500
from leads.views import error_404,error_400,error_403,error_500,error_401,error_405
# from campaign.views import AssignAgentView

handler404 = error_404
handler400 = error_400
handler403 = error_403
handler401 = error_401
handler405 = error_405
handler500 = error_500


app_name = "leads"

urlpatterns = [
    path('',LeadListView.as_view(),name="lead-list"),
    path('facebook/',lead_form_submissions,name="facebook-lead-list"),
    # path('<int:campaign_id>/<int:pk>/',LeadDetailView.as_view(),name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('<int:campaign_id>/<int:pk>/update/', LeadUpdateView.as_view(),name="lead-update"),
    path('<int:campaign_id>/<int:pk>/delete/', LeadDeleteView.as_view(),name="lead-delete"),
    # path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name="assign-agent"),
    path('<int:campaign_id>/<int:pk>/category/', LeadCategoryUpdateView.as_view(),name="lead-category-update"),
    path('leads/followups/', FollowUpListView.as_view(), name='followup-list'), 
    path('settings', SettingsPageView.as_view(), name='settings'), 
    # path('<int:campaign_id>/followups/', FollowUpView.as_view(), name='followup-leads'),
    path('<int:campaign_id>/<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),    
    path('followups/<int:campaign_id>/<int:pk>/update/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('<int:pk>/create/', LeadCreateView.as_view(),name="lead-create"),
    # path('<int:pk>/whatsapp/', WhatsappMessagingView.as_view(), name='lead-whatsapp'),
    # path('create-category/', CategoryCreateView.as_view(),name="category-create"),
    path('categories/' , CategoryListView.as_view(), name="category-list"),
    # path('categories/<int:pk>/update/' ,CategoryUpdateView.as_view(), name="category-update"),
    # path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(),name="category-delete"),
    # path('categories/' , CategoryDetailView.as_view(), name="category-detail"),
    # path('upload/', UploadFileView.as_view(), name='upload'),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kybic CRM</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.svg' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel=" stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    	<!--Regular Datatables CSS-->
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
	<!--Responsive Extension Datatables CSS-->
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    
    <style>
    section{
        width:95%;
        margin:auto;
    }
        .lead {
            padding:10px 6px;
            margin-top: 10px;
            background-color: #f99898;
            width: 100%;
        }


    </style>
</head>
<body>

     {% include "navbar.html" %}
     
    {% block content %}
    
    {% endblock content %}

    {% include "scripts.html" %}
    {% include "footer.html" %}



</body>
</html>

templates/dashboard.html
{% extends "main.html" %}
{% load static %}



{% block content %}


    <div class="sub-container-1 " >
        <h1 ></h1>

       
        <!-- # Total Count Session -->

        <div class="total-count pt-10   mb-3 pl-auto md:pl-10">
            <p class="font-bold text-gray-400 pl-10 md:sm-0" id="dateRangeText" style="width: 100%;color: black;"> <strong class="" >
              {% if start_date_str and end_date_str  %}

              From {{start_date_str}}  To  {{end_date_str}}
              {% else %}
              Last 30 Days
              {% endif %}
            </strong> </p>

            <div class="flex justify-between rounded-xl shadow-md p-2" style=" width: auto;position: absolute;background-color: #037af4;right: 10px;top: 50px;">
                <div class="flex justify-between flex-col" style="width: auto; background-color: transparent;">
                    
                    <button class="text-sm  text-gray-500 " id="showFormButton" style="width: auto;text-align: end; color: #ffffff;letter-spacing: .08rem;">Select Date</button>
                    <div id="formContainer" class="px-5 py-0 rounded-xl mb-0" style="display: none; background-color: transparent; flex-direction: row; align-items: center;">
                      
                     
                      <hr>
                      <form method="get" action="." class="font-medium text-s flex flex-col flex-wrap items-start mt-5" style="display: flex; flex-direction: column;flex-wrap: wrap;align-items: center;margin: 10px;">
                        <div class="mb-3">
                          <label for="start_date">Start:</label>
                          <input type="date" id="start_date" name="start_date" value="{{ start_date_str }}">
                        </div>
                        <div class="mb-3">
                          <label for="end_date">End:</label>
                          <input type="date" id="end_date" name="end_date" value="{{ end_date_str }}">
                        </div>  
                        <button type="submit" class="button">Apply</button>
                      </form>
                    </div>
                    <!-- Add a button or text element to trigger the form visibility -->
                    
                    <!-- Alternatively, use a text element instead of a button -->
                    <!-- <p id="showFormButton" class="text-blue-600 cursor-pointer">Show Form</p> -->
                  </div>
                  
                 <!-- <img src="{% static 'images/dashboardbg.png' %}" alt="" class="w-60" > -->
            </div>
            <!-- <div class="one ">
                <div class="text">
                    <p>Total</p>
                    <h4>Campaigns</h4>
                <h2>{{total_campaign_count}}</h2>
                <p>
                    <a href="{% url 'campaign:campaign-list' %}" class="flex flex-row items-center flex-wrap">
                        View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                    </a>
                </p>
                </div>
            </div> -->
            <div class="one">
                <div class="text">
                  <p>Total</p>
                    <h4> Leads</h4>
                <h2>{{total_lead_count_date}}</h2>
                <p>
                    <a href="{% url 'leads:category-list' %}" class="flex flex-row items-center flex-wrap">
                        View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                    </a>
                </p>
                </div>
            </div>
            <div class="one">
                <div class="text">
                    <p>Leads to</p>
                    <h4>Follow Up</h4>
                <h2>{{followup_in_date_range}}</h2>                
                <p>
                    <a href="{% url 'leads:followup-list' %}" class="flex flex-row items-center flex-wrap">
                        View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                    </a>
                </p>
                </div>
            </div>
            <div class="one">
                <div class="text">
                    <p>Total</p>
                    <h4>Converted</h4>
                <h2>{{leads_converted_in_date_range}}</h2>
                <p>
                    <a href="{% url 'leads:category-list' %}" class="flex flex-row items-center flex-wrap">
                        View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                    </a>
                </p>
                </div>
                
            </div>
            <div class="one">
              <div class="text">
                  <p>Total New</p>
                  <h4> Leads</h4>
              <h2>{{new_lead_count_date}}</h2>
              <p>
                  <a href="{% url 'leads:category-list' %}" class="flex flex-row items-center flex-wrap">
                      View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                  </a>
              </p>
              </div>
              
          </div>
          <div class="one">
            <div class="text">
                <p>Total</p>
                <h4>Rejected</h4>
            <h2>{{rejected_in_date_range}}</h2>
            <p>
                <a href="{% url 'leads:category-list' %}" class="flex flex-row items-center flex-wrap">
                    View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                </a>
            </p>
            </div>
            
        </div>
        <div class="one">
          <div class="text">
              <p>Total</p>
              <h4>Amount</h4>
          <h2>2000</h2>
          <p>
              <a href="{% url 'leads:category-list' %}" class="flex flex-row items-center flex-wrap">
                  View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
              </a>
          </p>
          </div>
          
      </div>
            
            
        </div>
        <!-- <img src="{% static 'images/dashboardbg.png' %}" alt="" class="w-60"> -->
        <div class="total-leads flex flex-row items-baseline pl-auto md:pl-10" style="height:auto;overflow:scroll;">
            <!-- # chart -->
            {% include "chart.html" %}
          </div>
            <!-- <div class=" px5  rounded  mx-auto date-result">
                <h1 class="text-lg font-bold text-gray-500 ">Your Results</h1><hr style="width:100%">
                
                <div>
                  <p >Total <br> Leads</p>
                  <span >{{total_lead_count_date}}</span>
                </div>
                <div>
                  <p >New <br> Leads</p>
                  <span >{{new_lead_count_date}}</span>
                </div>
                <div>
                  <p >Follow up <br> Leads</p>
                  <span >{{followup_in_date_range}}</span>
                </div>
                <div>
                  <p >Converted <br> Leads</p>
                  <span >{{leads_converted_in_date_range}}</span>
                </div>
                <div>
                  <p >Rejected <br> Leads</p>
                  <span >{{rejected_in_date_range}}</span>
                </div>
              </div> 
         -->
 

        <!-- # New Lead Session -->

  <!-- <h1 class="text-1xl font-bold  ml-5">Campaigns</h1> -->
    <div class="total-count-2 pt-5 border border-b-indigo-100 pl-auto md:pl-10">
        <div class="" style="width:100%">
            <p class="font-bold text-gray-400 pl-10"><strong class="uppercase text-gray-600">{{user.username}}</strong> , These are the Campaigns.</p>
        </div>
        
        {% for campaign in campaigns %}
        <div class="one">
            <div class="text">
                <h5>Campaign</h5>
                <h4 class="uppercase">{{ campaign.name }}</h4>
                {% comment %} <h5>Total Leads:{{ campaign.lead_count }}</h5> {% endcomment %}
                <p>
                    <a href="{% url 'campaigns:campaign-detail' campaign.pk %}" class="flex flex-row items-center flex-wrap">
                        View More <i class="bx bx-chevrons-right " style="margin-bottom:-2px"></i>
                    </a>
                </p>
            </div>
        </div>
        {% empty %}
        No campaigns found.
        {% endfor %}
    </div>
    </div>
</div>
<script>
    // Function to update the "Last 30 days" text with the selected date range
    function updateDateRangeText(startDate, endDate) {
      const dateRangeText = document.getElementById('dateRangeText');
      dateRangeText.innerHTML = ` <strong class="uppercase text-gray-600">From ${startDate} - To ${endDate}</strong>`;
    }
  
    // Function to handle form submission
    function handleSubmit(event) {
    //   event.preventDefault(); // Prevent the form from submitting normally (we'll handle it with JavaScript)
  
      // Get the selected start and end dates from the form
      const startDate = document.getElementById('start_date').value;
      const endDate = document.getElementById('end_date').value;
  
      // Update the "Last 30 days" text with the selected date range
      updateDateRangeText(startDate, endDate);
  
      // Optionally, you can perform additional actions here, like submitting the form data to the server via AJAX
    }
  
    // Get references to the form and add a submit event listener
    const form = document.querySelector('form');
    form.addEventListener('submit', handleSubmit);
  </script>
  
<script>
    // Get references to the form container and the button (or text)
    const formContainer = document.getElementById('formContainer');
    const showFormButton = document.getElementById('showFormButton');
  
    // Function to toggle the visibility of the form container
    function toggleFormVisibility() {
      if (formContainer.style.display === 'none') {
        formContainer.style.display = 'flex';
      } else {
        formContainer.style.display = 'none';
      }
    }
  
    // Add a click event listener to the button (or text) to trigger the visibility toggle
    showFormButton.addEventListener('click', toggleFormVisibility);
  </script>
  

<!-- JS File -->
<script type="text/javascript" src={% static 'js/main.js' %}>
</script>


  
{% endblock content %}




    
  
   

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kybic CRM</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.svg' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel=" stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    	<!--Regular Datatables CSS-->
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
	<!--Responsive Extension Datatables CSS-->
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    <script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>

    
    <style>
        section{
            width:100%;
            margin:auto;
        }
        .lead {
            padding:10px 6px;
            margin-top: 10px;
            background-color: #f99898;
            width: 100%;
        }
        .bg-color-1 {
        background-color:#937DC2 ; /* greenish */
        background: linear-gradient(45deg, #7941fc83,#d04beb7e);
        }

        .bg-color-2 {
        background-color: #C689C6; /* Green */
        background: linear-gradient(45deg, #5da5f7, #a2ccfd);
        }

        .bg-color-3 {
        background-color: #ff9696; /* Blue */
        background: linear-gradient(45deg, #1fb983,#47f3ff);
        }

        .bg-color-4 {
        background-color: #A0C49D; /* orrange */
        background: linear-gradient(45deg, #ffe277, #ffea9f);
        }
        


          /* Style The Dropdown Button */
                             /* .dropbtn {
                              background-color: #4CAF50;
                              color: white;
                              padding: 16px;
                              font-size: 16px;
                              border: none;
                              cursor: pointer;
                            } */
                            
                            /* The container <div> - needed to position the dropdown content */
                            .dropdown {
                              position: relative;
                              display: inline-block;
                              width: 100%;
                            }
                            
                            /* Dropdown Content (Hidden by Default) */
                            .dropdown-content {
                              display: none;
                              position: absolute;
                              background-color: #212424f5;
                              min-width: 160px;
                              z-index: 1;
                            }
                            
                            /* Links inside the dropdown */
                            .dropdown-content a {
                              color: black;
                              padding: 4px 16px;
                              text-decoration: none;
                              display: block;
                            }
                            
                            
                            /* Show the dropdown menu on hover */
                            .dropdown:hover .dropdown-content {
                              display: block;
                            }
                            
    </style>
</head>
<body>
    <!-- <style contenteditable style="display: block;">
        body{
            background-color:red;
        }
    </style> -->
    <div class="   mx-auto mt-1 pb-2 shadow" >
        <nav class="max-w-8xl flex justify-between   px-2 mb-0">
            <div class="container mx-auto flex flex-wrap items-center justify-between flex-row-reverse">
                <a href="{% url 'landing-page' %}" class="flex mr-12">
                <img src="{% static 'images\kybicicon.png' %}" alt="" style="width:30px;margin:auto 10px;">    
                <span class="self-center text-lg font-semibold whitespace-nowrap">KYBIC</span>

                </a>
                <div class="flex md:order-2">           
                
                </div>            
            </div>
        </nav>  
     </div> 
  
     
    <div class="side">
        <div class="toggle">
            <i class="bx bx-menu-alt-right"></i>
        </div>
    </div>
    <div class="main">   
    
        <div class="sidebar" style="background: linear-gradient(45deg, #1E212D, #1E212D);">         
        
            <div class="logo">
                <img class="user-icon" alt="hero" src="{% static 'images/user1.jpg' %}">
                <!-- <img src="" alt="pro pic"> -->
                {% if request.user.is_authenticated %}
                        <h3>{{request.user.username}}</h3>
                {% endif %}
            </div>
        
            <nav>    
                {% if request.user.is_organiser %}
                <div class="nav-title">
                    Admin
                </div>
                {% else %}
                <div class="nav-title">
                    Staff
                </div>
                {% endif %}

                <ul>
                    <a href="{% url 'dashboard'%}">
                    <li class="nav-item  ">
                        <i class="bx bxs-dashboard"></i>
                        <span>Dashboard</span>
                    </li>
                    </a>
                    <a href="{% url 'leads:followup-list' %}">
                        <li class="nav-item  ">
                            <i class="bx bxs-calendar-edit"></i>
                            <span>Follow up</span>
                        </li>
                        </a>
                        <a href="{% url 'campaign:campaign-list'  %}" class="text-gray-500 hover:text-blue-500">
                            <li class="nav-item">
                                <i class="bx bxs-buildings"></i>
                                <span>Campaigns</span>
                            </li>
                        </a>
                    </ul>                         
                   
                        <a href="{% url 'leads:category-list'  %}" class="text-gray-500 hover:text-blue-500">
                        <li class="nav-item">
                            <i class="bx bxs-circle-three-quarter"></i>
                            <span>Overview</span>
                        </li>
                        </a>
                       
                        
                            <div class="dropdown"> 
                                <li class="nav-item">
                                <i class="bx bxs-user-badge"></i>
                                <span>Profile </span>
                               </li> 
                              <div class="dropdown-content">
                               {% if request.user.is_organiser %}
                                    <a href="{% url 'agents:agent-list'%}">
                                        <li class="nav-item">
                                            <i class="bx bxs-user-circle"></i>
                                            <span>Staff</span>
                                        </li>
                                 <a href="{% url 'leads:settings'%}">
                                        <li class="nav-item">
                                            <i class="bx bxs-brightness"></i>
                                            <span>settings</span>
                                        </li>                                    
                                    </a>
                                     {% else %}
                    {% endif %}
                                      
                                    <a href="{% url 'logout' %}" ><li class="nav-item">
                                        <i class="bx bxs-log-out"></i>
                                        <span>Logout</span>
                                    </li>
                                </a>
                              </div>
                            </div>
                        <!-- <a href="{% url 'agents:agent-list'%}">
                        <li class="nav-item">
                            <i class="bx bxs-user-badge"></i>
                            <span>Staff</span>
                        </li>
                        </a>                                    -->
                   
                    {% comment %} <a href="{% url 'create_notification'  %}" class="text-gray-500 hover:text-blue-500">
                        <li class="nav-item">
                            <i class="bx bxs-buildings"></i>
                            <span>Notifications</span>
                        </li>
                    </a> {% endcomment %}
                    <!-- <a href="{% url 'logout' %}" ><li class="nav-item">
                        <i class="bx bxs-log-out"></i>
                        <span>Logout</span>
                    </li></a> -->
                    
                <hr>        
                <div class="nav-title">
                    Supports
                </div>        
                <ul>
                    <a href="tel:+919061713244">
                        <li class="nav-item">
                            <i class="bx bxs-help-circle"></i>
                            <span>Get Help</span>
                        </li>
                    </a>
                    <a href="https://wa.me/919061713244">
                        <li class="nav-item">
                            <i class="bx bxs-message-dots"></i>
                            <span>Send Feedback</span>
                        </li>
                    </a>
                    {% comment %} <a href="{% url 'fb_login'%}">
                        <li class="nav-item">
                            <i class="bx bxs-message-dots"></i>
                            <span>Facebook Login</span>
                        </li>
                    </a> {% endcomment %}
                    
                </ul>          
            </nav>
        </div>  
  
    {% block content %}
    
    {% endblock content %}

    </div>
    <!-- Main div ends -->
<script>
  const cards = document.querySelectorAll('.campaign-item');
  const one = document.querySelectorAll('.one');
  const staffs = document.querySelectorAll('.staff-badge');
  const thead = document.querySelectorAll('table thead');
  
  const colors = ['bg-color-1', 'bg-color-2', 'bg-color-3', 'bg-color-4'];
  let colorIndex = 0;
  cards.forEach(card => {
    card.classList.add(colors[colorIndex]);
    colorIndex = (colorIndex + 1) % colors.length;
  });
  one.forEach(one => {
    one.classList.add(colors[colorIndex]);
    colorIndex = (colorIndex + 1) % colors.length;
  });
  staffs.forEach(staff => {
    staff.classList.add(colors[colorIndex]);
    colorIndex = (colorIndex + 1) % colors.length;
  });
  thead.forEach(thead => {
    thead.classList.add(colors[colorIndex]);
    colorIndex = (colorIndex + 1) % colors.length;
  });
</script>
<script>
    const navItems = document.querySelectorAll('.nav-item');

navItems.forEach(item => {
  item.addEventListener('click', () => {
    // remove active class from all items
    navItems.forEach(navItem => {
      navItem.classList.remove('active');
    });

    // add active class to clicked item
    item.classList.add('active');
  });
});

</script>


</body>
</html>